// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface SimpleContract$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "SimpleContract";
  readonly sourceName: "contracts/SimpleContract.sol";
  readonly abi: [];
  readonly bytecode: "0x6080604052348015600e575f80fd5b50603e80601a5f395ff3fe60806040525f80fdfea264697066735822122090d16639608c7a85c2648c97b399cba9ffda439fce739319c80006eed3414cf464736f6c63430008140033";
  readonly deployedBytecode: "0x60806040525f80fdfea264697066735822122090d16639608c7a85c2648c97b399cba9ffda439fce739319c80006eed3414cf464736f6c63430008140033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/SimpleContract.sol";
  readonly buildInfoId: "solc-0_8_20-c9c3d6024b89bac4d73aafe57f1b4df85f9050c3";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["SimpleContract"]: SimpleContract$Type;
    ["contracts/SimpleContract.sol:SimpleContract"]: SimpleContract$Type;
  }
}